name: Secret Scanning

on: [push, pull_request]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install TruffleHog
        run: |
          curl -LO https://github.com/dxa4481/truffleHog/releases/download/v2.0.0/trufflehog_linux_amd64.tar.gz
          tar xzf trufflehog_linux_amd64.tar.gz
          chmod +x trufflehog
          sudo mv trufflehog /usr/local/bin/

      - name: Run TruffleHog
        run: trufflehog --regex --entropy=False https://github.com/ваш/репозиторий
