name: Scan for Secrets
run: ls -as

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install truffleHog
        run: pip install truffleHog

      - name: Run truffleHog
        run: trufflehog --json . > trufflehog-report.json

      - name: Upload results
        uses: actions/upload-artifact@v3
        with:
          name: trufflehog-report
          path: trufflehog-report.json
